import os
import pandas as pd

def merge_nhanes_domains():
    print("🔄 Initializing NHANES Mood & Sleep Dataset Merger...")
    
    # Define file paths relative to the project root directory
    depression_path = "datasets/nhanes_depression_clean.csv"
    sleep_path = "datasets/nhanes_sleep_clean.csv"
    output_path = "datasets/nhanes_joined_mood_sleep.csv"
    
    # Verification: Ensure both source datasets exist before loading
    if not os.path.exists(depression_path) or not os.path.exists(sleep_path):
        print("❌ Error: Missing source datasets. Ensure both clean NHANES files exist in the datasets/ directory.")
        return

    # Load datasets
    df_depression = pd.read_csv(depression_path)
    df_sleep = pd.read_csv(sleep_path)
    
    print(f"📊 Loaded Depression Data: {df_depression.shape[0]} rows, {df_depression.shape[1]} columns")
    print(f"📊 Loaded Sleep Data:      {df_sleep.shape[0]} rows, {df_sleep.shape[1]} columns")
    
    # Determine the join key (NHANES defaults to 'SEQN' as the participant identifier)
    join_key = 'SEQN'
    
    if join_key not in df_depression.columns or join_key not in df_sleep.columns:
        # Fallback check if the column name varies slightly
        print(f"⚠️ Column '{join_key}' not found automatically. Searching for common identifiers...")
        common_cols = list(set(df_depression.columns).intersection(set(df_sleep.columns)))
        if not common_cols:
            print("❌ Error: No common identifier column found between datasets to perform the merge.")
            return
        join_key = common_cols[0]
        print(f"🔄 Selected common identifier key: '{join_key}'")

    # Perform the inner join operation
    print(f"🔗 Merging datasets via Inner Join on key: '{join_key}'...")
    df_joined = pd.merge(df_depression, df_sleep, on=join_key, how='inner')
    
    # Remove any duplicate columns generated by the merge if necessary
    # (Keeps the first instance and drops the suffix versions if there's overlap)
    df_joined = df_joined.loc[:, ~df_joined.columns.duplicated()]
    
    # Save the resulting structured table back to your datasets/ folder
    df_joined.to_csv(output_path, index=False)
    
    print("---")
    print(f"🎉 Success! Combined dataset written to: -> {output_path}")
    print(f"📈 Final Output Array Dimensions: {df_joined.shape[0]} rows, {df_joined.shape[1]} columns")

if __name__ == "__main__":
    # Expects execution from the project root directory: python scripts/merge_nhanes_mood_sleep.py
    merge_nhanes_domains()